### ISSUE TITLE
The GPU utilization rate is low during training, and the training is very slow！

### ISSUE THREAD

**Issue by tms2003** [Peterande/D-FINE#5]
I use the following command to train on a GPU card. The GPU is generally less than 10%. Why is the training so low?

 torchrun  train.py -c configs/dfine/custom/dfine_hgnetv2_l_custom.yml --use-amp --seed=0
This's my config.xml
```
task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 11 # your dataset classes
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /tms/data/coco_2024/images
    ann_file: /tms/data/coco_2024/annotations/result.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 8
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /tms/data/coco_2024/images
    ann_file: /tms/data/coco_2024/annotations/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 8
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion

```
This is the first output:

```
Epoch: [0]  [   0/3999]  eta: 8:34:10  lr: 0.000000  loss: 64.9147 (64.9147)  loss_vfl: 0.2810 (0.2810)  loss_bbox: 2.2343 (2.2343)  loss_giou: 1.9365 (1.9365)  loss_fgl: 0.2977 (0.2977)  loss_vfl_aux_0: 0.2856 (0.2856)  loss_bbox_aux_0: 2.2343 (2.2343)  loss_giou_aux_0: 1.9365 (1.9365)  loss_fgl_aux_0: 0.2977 (0.2977)  loss_vfl_aux_1: 0.2942 (0.2942)  loss_bbox_aux_1: 2.2343 (2.2343)  loss_giou_aux_1: 1.9365 (1.9365)  loss_fgl_aux_1: 0.2977 (0.2977)  loss_vfl_aux_2: 0.2607 (0.2607)  loss_bbox_aux_2: 2.2343 (2.2343)  loss_giou_aux_2: 1.9365 (1.9365)  loss_fgl_aux_2: 0.2977 (0.2977)  loss_vfl_aux_3: 0.2947 (0.2947)  loss_bbox_aux_3: 2.2343 (2.2343)  loss_giou_aux_3: 1.9365 (1.9365)  loss_fgl_aux_3: 0.2977 (0.2977)  loss_vfl_aux_4: 0.2991 (0.2991)  loss_bbox_aux_4: 2.2343 (2.2343)  loss_giou_aux_4: 1.9365 (1.9365)  loss_fgl_aux_4: 0.2977 (0.2977)  loss_vfl_pre: 0.2856 (0.2856)  loss_bbox_pre: 2.2343 (2.2343)  loss_giou_pre: 1.9365 (1.9365)  loss_vfl_enc_0: 0.2507 (0.2507)  loss_bbox_enc_0: 2.2343 (2.2343)  loss_giou_enc_0: 1.9365 (1.9365)  loss_vfl_dn_0: 0.8105 (0.8105)  loss_bbox_dn_0: 1.0030 (1.0030)  loss_giou_dn_0: 1.3419 (1.3419)  loss_fgl_dn_0: 0.8430 (0.8430)  loss_vfl_dn_1: 0.8896 (0.8896)  loss_bbox_dn_1: 1.0030 (1.0030)  loss_giou_dn_1: 1.3419 (1.3419)  loss_fgl_dn_1: 0.8430 (0.8430)  loss_vfl_dn_2: 0.9038 (0.9038)  loss_bbox_dn_2: 1.0030 (1.0030)  loss_giou_dn_2: 1.3419 (1.3419)  loss_fgl_dn_2: 0.8430 (0.8430)  loss_vfl_dn_3: 0.8555 (0.8555)  loss_bbox_dn_3: 1.0030 (1.0030)  loss_giou_dn_3: 1.3419 (1.3419)  loss_fgl_dn_3: 0.8430 (0.8430)  loss_vfl_dn_4: 0.8955 (0.8955)  loss_bbox_dn_4: 1.0030 (1.0030)  loss_giou_dn_4: 1.3419 (1.3419)  loss_fgl_dn_4: 0.8430 (0.8430)  loss_vfl_dn_5: 0.8726 (0.8726)  loss_bbox_dn_5: 1.0030 (1.0030)  loss_giou_dn_5: 1.3419 (1.3419)  loss_fgl_dn_5: 0.8430 (0.8430)  loss_vfl_dn_pre: 0.8105 (0.8105)  loss_bbox_dn_pre: 1.0030 (1.0030)  loss_giou_dn_pre: 1.3419 (1.3419)  time: 7.7145  data: 3.3224  max mem: 15826
Epoch: [0]  [ 100/3999]  eta: 1:47:07  lr: 0.000003  loss: 54.7667 (58.6890)  loss_vfl: 0.5742 (0.4503)  loss_bbox: 1.3285 (1.7103)  loss_giou: 1.4214 (1.6404)  loss_fgl: 0.6612 (0.5103)  loss_vfl_aux_0: 0.4985 (0.3966)  loss_bbox_aux_0: 1.3807 (1.7359)  loss_giou_aux_0: 1.4401 (1.6587)  loss_fgl_aux_0: 0.6462 (0.5032)  loss_vfl_aux_1: 0.5386 (0.4283)  loss_bbox_aux_1: 1.3580 (1.7269)  loss_giou_aux_1: 1.4328 (1.6523)  loss_fgl_aux_1: 0.6526 (0.5057)  loss_vfl_aux_2: 0.5366 (0.4177)  loss_bbox_aux_2: 1.3494 (1.7219)  loss_giou_aux_2: 1.4304 (1.6486)  loss_fgl_aux_2: 0.6551 (0.5069)  loss_vfl_aux_3: 0.5562 (0.4359)  loss_bbox_aux_3: 1.3402 (1.7171)  loss_giou_aux_3: 1.4273 (1.6454)  loss_fgl_aux_3: 0.6579 (0.5082)  loss_vfl_aux_4: 0.5854 (0.4475)  loss_bbox_aux_4: 1.3354 (1.7137)  loss_giou_aux_4: 1.4249 (1.6427)  loss_fgl_aux_4: 0.6596 (0.5093)  loss_vfl_pre: 0.4954 (0.3937)  loss_bbox_pre: 1.4076 (1.7411)  loss_giou_pre: 1.4508 (1.6630)  loss_vfl_enc_0: 0.4766 (0.3814)  loss_bbox_enc_0: 1.4723 (1.7543)  loss_giou_enc_0: 1.4959 (1.6754)  loss_vfl_dn_0: 0.4158 (0.5894)  loss_bbox_dn_0: 0.9358 (0.9461)  loss_giou_dn_0: 1.3314 (1.3310)  loss_fgl_dn_0: 0.8526 (0.8504)  loss_vfl_dn_1: 0.4136 (0.6395)  loss_bbox_dn_1: 0.9422 (0.9496)  loss_giou_dn_1: 1.3315 (1.3316)  loss_fgl_dn_1: 0.8487 (0.8491)  loss_vfl_dn_2: 0.4224 (0.5959)  loss_bbox_dn_2: 0.9394 (0.9516)  loss_giou_dn_2: 1.3293 (1.3318)  loss_fgl_dn_2: 0.8433 (0.8472)  loss_vfl_dn_3: 0.4158 (0.5715)  loss_bbox_dn_3: 0.9378 (0.9543)  loss_giou_dn_3: 1.3285 (1.3322)  loss_fgl_dn_3: 0.8406 (0.8459)  loss_vfl_dn_4: 0.4233 (0.6076)  loss_bbox_dn_4: 0.9366 (0.9570)  loss_giou_dn_4: 1.3281 (1.3324)  loss_fgl_dn_4: 0.8386 (0.8448)  loss_vfl_dn_5: 0.4246 (0.5783)  loss_bbox_dn_5: 0.9348 (0.9590)  loss_giou_dn_5: 1.3261 (1.3325)  loss_fgl_dn_5: 0.8368 (0.8437)  loss_vfl_dn_pre: 0.4163 (0.5897)  loss_bbox_dn_pre: 0.9320 (0.9444)  loss_giou_dn_pre: 1.3310 (1.3308)  loss_ddf_aux_0: 0.0068 (0.0026)  loss_ddf_aux_1: 0.0042 (0.0015)  loss_ddf_aux_2: 0.0020 (0.0008)  loss_ddf_aux_3: 0.0010 (0.0003)  loss_ddf_aux_4: 0.0003 (0.0001)  loss_ddf_dn_0: 0.0043 (0.0017)  loss_ddf_dn_1: 0.0031 (0.0012)  loss_ddf_dn_2: 0.0016 (0.0006)  loss_ddf_dn_3: 0.0007 (0.0003)  loss_ddf_dn_4: 0.0002 (0.0001)  time: 1.5149  data: 0.0414  max mem: 33922

```
In addition, if you do not use torchrun, you will get an error when running train.py directly with python.
